name: Django CI

on:
  push:
    branches: ["main"]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
      
      - name: Check Docker version
        run: |
          docker --version
          docker compose version
      
      - name: Build and start services
        run: docker compose up --build -d
      
      - name: Wait for services to be ready
        run: sleep 15
      
      - name: Check all containers are running
        run: docker compose ps

      - name: Check Django logs
        run: docker compose logs django-app

      - name: Check cache logs
        run: docker compose logs cache
      
      - name: Test redis endpoint
        run: curl -f http://localhost:8000/api/redis-test/

      - name: Check Django logs after redis test
        run: docker compose logs django-app

      - name: Test create book endpoint
        run: |
          curl -f -X POST http://localhost:8000/api/books/ \
            -H "Content-Type: application/json" \
            -d '{"name": "The Pragmatic Programmer", "author": "David Thomas"}'

      - name: Test get all books endpoint
        run: |
          curl -f http://localhost:8000/api/books/
      
      - name: Tear down
        run: docker compose down

